In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
filename = "foia_up_to_150k_WA.csv"

df = pd.read_csv(filename, parse_dates=['DateApproved'])

In [5]:
df

,LoanAmount,City,State,Zip,NAICSCode,BusinessType,RaceEthnicity,Gender,Veteran,NonProfit,JobsRetained,DateApproved,Lender,CD
0,149992.0,BELLINGHAM,WA,98225.0,NaN,Subchapter S Corporation,Unanswered,Unanswered,Unanswered,NaN,11.0,2020-05-01,"JPMorgan Chase Bank, National Association",WA - 01
1,149980.0,SPOKANE VALLEY,WA,99216.0,621210.0,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,12.0,2020-04-29,Banner Bank,WA - 05
2,149975.0,KIRKLAND,WA,98033.0,339999.0,Subchapter S Corporation,Unanswered,Unanswered,Unanswered,NaN,6.0,2020-04-16,Seattle Bank,WA - 01
3,149950.0,PORT ORCHARD,WA,98367.0,238210.0,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,10.0,2020-06-13,"Kabbage, Inc.",WA - 06
4,149922.0,BURLINGTON,WA,98233.0,999990.0,Subchapter S Corporation,Unanswered,Unanswered,Unanswered,NaN,12.0,2020-05-03,Cross River Bank,WA - 01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85197,9.0,PUYALLUP,WA,98373.0,621340.0,Sole Proprietorship,Unanswered,Unanswered,Unanswered,NaN,1.0,2020-05-05,"Bank of America, National Association",WA - 10
85198,9.0,SPOKANE,WA,99217.0,453991.0,Corporation,Unanswered,Unanswered,Unanswered,NaN,4.0,2020-05-03,"Bank of America, National Association",WA - 05
85199,2.0,NORTH BEND,WA,98045.0,541611.0,Subchapter S Corporation,Unanswered,Male Owned,Unanswered,NaN,42.0,2020-04-27,UniBank,WA - 01
85200,2.0,SAMMAMISH,WA,98074.0,541213.0,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,3.0,2020-05-17,"Bank of America, National Association",WA - 01
85201,1.0,TUKWILA,WA,98188.0,314999.0,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,2.0,2020-05-02,"Bank of America, National Association",WA - 09

In [6]:
df['JobsRetained'].sum()

351522.0

In [7]:
df['BusinessType'].value_counts()

Limited  Liability Company(LLC)        31621
Corporation                            22624
Sole Proprietorship                    12337
Subchapter S Corporation               10791
Non-Profit Organization                 2748
Self-Employed Individuals               1937
Independent Contractors                 1461
Partnership                              719
Limited Liability Partnership            403
Professional Association                 366
Cooperative                               51
Non-Profit Childcare Center               38
Joint Venture                             19
Trust                                     11
Employee Stock Ownership Plan(ESOP)        8
Tenant in Common                           3
Name: BusinessType, dtype: int64